### ISSUE TITLE
Check for illegal characters in sandbox names.

### ISSUE THREAD

**Issue by jsi** [enonic/cli-enonic#264]
On Unix systems and Mac, there is only one character that is illegal when creating folders, and that is /.
I tried creating a sandbox named "Hey/all", and it was created without problems, but could not be used.  What happened was that the sandbox was created in the subfolder "all" of "Hey", which made it impossible to start.

I have not tested this on Windows, but on Windows, there are a number of illegal characters: https://stackoverflow.com/questions/1976007/what-characters-are-forbidden-in-windows-and-linux-directory-names

I have tested all these special characters of Windows on my Mac, and to create them on Mac works without problems, but some of them, like <, >, " and | have a special impact on the command execution on Linux, so the sandbox names must be contained in single quotes.

Running sandboxes with these names is another problem that I have tried to test, but not exhaustively.  Some characters have special meaning in file paths that cause problems, even if the sandbox can be created without quotes.  For instance, when starting a sandbox with a name that ends with an asterisk, the following error message appears when starting XP:

```
14:47:16,638 |-ERROR in ch.qos.logback.core.joran.spi.Interpreter@15:14 - RuntimeException in Action for tag [appender] java.util.regex.PatternSyntaxException: Dangling meta character '*' near index 39
/Users/sivesind/.enonic/sandboxes/A1:/?*/home/logs/server.\d{4}-\d{2}-\d{2}.\d{1,2}.log
                                       ^
	at java.util.regex.PatternSyntaxException: Dangling meta character '*' near index 39
/Users/sivesind/.enonic/sandboxes/A1:/?*/home/logs/server.\d{4}-\d{2}-\d{2}.\d{1,2}.log
                                       ^
	at 	at java.base/java.util.regex.Pattern.error(Pattern.java:2027)
	at 	at java.base/java.util.regex.Pattern.sequence(Pattern.java:2202)
...
```

**This should probably be tested better, or we can just do it the simple way of reasoning:  Many of these characters may cause problems and should not be used.

I suggest making most of these characters illegal for sandbox names.  We don't need them anyway.**

**Comment by jsi** [comment]
The other characters should possibly be considered.  There may be other characters in the sandboxes that should be avoided.  For instance, when starting a sandbox with a name that ends with an asterisk, the following error message appears when starting XP:

```
14:47:16,638 |-ERROR in ch.qos.logback.core.joran.spi.Interpreter@15:14 - RuntimeException in Action for tag [appender] java.util.regex.PatternSyntaxException: Dangling meta character '*' near index 39
/Users/sivesind/.enonic/sandboxes/A1:/?*/home/logs/server.\d{4}-\d{2}-\d{2}.\d{1,2}.log
                                       ^
	at java.util.regex.PatternSyntaxException: Dangling meta character '*' near index 39
/Users/sivesind/.enonic/sandboxes/A1:/?*/home/logs/server.\d{4}-\d{2}-\d{2}.\d{1,2}.log
                                       ^
	at 	at java.base/java.util.regex.Pattern.error(Pattern.java:2027)
	at 	at java.base/java.util.regex.Pattern.sequence(Pattern.java:2202)
...
```
