### ISSUE TITLE
Unable to log and use cloud commands with CLI 

### ISSUE THREAD

**Issue by JonasRolstad** [enonic/cli-enonic#326]
When I attempt to write 'enonic cloud login' in the CLI I'm redirected to the 'Device Confirmation'-page and can click **Confirm**, press **Log in** and get the confirmation "Congratulations, you're all set!".
But in the CLI window I get the following:

```
Waiting for you to login .. panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x10 pc=0x8059ef]

goroutine 1 [running]:
cli-enonic/internal/app/commands/cloud/auth.Login(0xc0000d49b0, 0xc0000d49a0, 0xc0001b4630, 0xb20d59)
        /Users/ase/dev/cli-enonic/internal/app/commands/cloud/auth/auth_flow.go:72 +0x7f
cli-enonic/internal/app/commands/cloud.login(0xb1f800, 0x2, 0xc00016f6e0)
        /Users/ase/dev/cli-enonic/internal/app/commands/cloud/login.go:67 +0xa8
cli-enonic/internal/app/commands/cloud.glob..func1(0xc00018e580, 0x0, 0xc00017bb70)
        /Users/ase/dev/cli-enonic/internal/app/commands/cloud/login.go:32 +0x6d
github.com/urfave/cli.HandleAction(0xa46800, 0xb502e0, 0xc00018e580, 0xc00018e580, 0x0)
        /Users/ase/go/pkg/mod/github.com/urfave/cli@v1.22.5/app.go:524 +0xc5
github.com/urfave/cli.Command.Run(0xb20ec6, 0x5, 0x0, 0x0, 0x0, 0x0, 0x0, 0xb2d539, 0x15, 0x0, ...)
        /Users/ase/go/pkg/mod/github.com/urfave/cli@v1.22.5/command.go:173 +0x534
github.com/urfave/cli.(*App).RunAsSubcommand(0xc0001e01c0, 0xc00018e2c0, 0x0, 0x0)
        /Users/ase/go/pkg/mod/github.com/urfave/cli@v1.22.5/app.go:405 +0x8a9
github.com/urfave/cli.Command.startApp(0xb20c87, 0x5, 0x0, 0x0, 0x0, 0x0, 0x0, 0xb2b895, 0x13, 0x0, ...)
        /Users/ase/go/pkg/mod/github.com/urfave/cli@v1.22.5/command.go:372 +0x856
github.com/urfave/cli.Command.Run(0xb20c87, 0x5, 0x0, 0x0, 0x0, 0x0, 0x0, 0xb2b895, 0x13, 0x0, ...)
        /Users/ase/go/pkg/mod/github.com/urfave/cli@v1.22.5/command.go:102 +0x9aa
github.com/urfave/cli.(*App).Run(0xc0001e0000, 0xc00006e0c0, 0x3, 0x4, 0x0, 0x0)
        /Users/ase/go/pkg/mod/github.com/urfave/cli@v1.22.5/app.go:277 +0x73c
main.main()
        internal/app/cli.go:36 +0x1e9
```

Then attempting to do 'enonic cloud app install' just returns "Login with 'enonic cloud login'".

**Comment by alansemenov** [comment]
@JonasRolstad we tried it on several Windows machines with no luck reproducing... can you try it on a different PC? just trying to pin this down to a specific configuration maybe.

**Comment by alansemenov** [comment]
@JonasRolstad Will be fixed in a separate issue: https://github.com/enonic/cli-enonic/issues/329
